SOURCESPATH="WeatherApp"
TEMPLATESPATH="Common/Sourcery"
OUTPUTPATH="Common/Sourcery/Autogenerated"
CURRENTFRAMEWORKNAME="WeatherApp"

if which sourcery >/dev/null; then
  sourcery --sources "$SOURCESPATH" \
    --templates "$TEMPLATESPATH" \
    --output "$OUTPUTPATH" \
    --args module="$CURRENTFRAMEWORKNAME",import="Foundation",import="Combine"
fi