default_platform(:ios)

platform :ios do

  before_all do
    xcode_select("/Applications/Xcode_13.2.1.app")
  end

  desc "Lint all targets with Swiftlint."
  lane :lint do
    swiftlint(
      output_file: "swiftlint.json",
      reporter: "json"
      )
  end

  desc "Run unit tests in iOS sumilator."
  lane :tests do
    run_tests(
      # xcpretty has an issue with junit report and test in mutiples devices: https://github.com/fastlane/fastlane/issues/10276
      # devices: ["iPhone SE 13.6", "iPhone SE 14.0", "iPad Air 2 13.6", "iPad Air 2 14.0"],
      disable_concurrent_testing: true,
      output_types: "junit",
      output_directory: 'test',
      derived_data_path: 'build',
      buildlog_path: 'logs'
      )
  end

  desc "Archive project for tests."
  lane :archive_for_tests do
    build_app(
      configuration: "Debug",
      derived_data_path: "build",
      export_method: "development",
      output_name: "WeatherApp.ipa",
      xcargs: "build-for-testing",
      silent: true
      )
  end

end
