on: 
  pull_request:
  push:
    branches:
      - main
      - 'release/**'

name: Test
jobs:
  test:
    name: Test
    runs-on: macOS-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache CocoaPod
        uses: actions/cache@v2
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Ruby setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: CocoaPod install
        run: pod install

      - name: Install Tools
        run: |
          brew install sonar-scanner
          gem install slather

      - name: Setup secrets
        run: |
          cp WeatherApp/Preferences/Secrets_example.plist WeatherApp/Preferences/Secrets.plist
          /usr/libexec/PlistBuddy -c "Set :OpenWeatherAPIKey ${OPEN_WEATHER_API_KEY}" WeatherApp/Preferences/Secrets.plist
        env: 
          OPEN_WEATHER_API_KEY: ${{ secrets.OPEN_WEATHER_API_KEY }}

      - name: Build and test
        run: bundle exec fastlane tests

      - name: Slather
        run: |
          slather coverage --sonarqube-xml ${params} ${project}
        env:
          project: 'WeatherApp.xcodeproj'
          params: '
          --build-directory ./build
          --output-directory ./reports
          --scheme WeatherApp
          --binary-basename WeatherApp
          --binary-basename Common'

      - name: SwiftLint
        run: |
           bundler exec fastlane run swiftlint output_file:"./reports/swiftlint.json" reporter:"json" ignore_exit_status:"true"

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: 'Save Xcode build log'
        uses: actions/upload-artifact@v3
        with:
          name: WeatherApp-WeatherApp.log
          path: logs
          retention-days: 5
        
